[phases.setup]
nixPkgs = ['php83', 'php83Extensions.mysqli', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql']

[phases.build]
cmds = ['echo "Building Werewolf Game..."']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'